// @ts-check
/**
 * Baseline (golden-file) calculation tests for every case-study calculator.
 *
 * For each dashboard and each named scenario we set the scenario's inputs, let
 * the model run, and compare every numeric output against
 * tests/case_studies/baselines/<key>.baseline.json.
 *
 * These tests are about ARITHMETIC, not markup: only computed values are
 * captured, so a restyle passes and a changed formula fails.
 *
 *   npm run test:case-studies          # assert against the baselines
 *   npm run test:case-studies:update   # rewrite the baselines after an intended change
 */

const { test, expect } = require('@playwright/test');
const { DASHBOARDS } = require('./dashboards.config');
const { UPDATE, readBaseline, writeBaseline, runScenario, baselinePath } = require('./baseline');

for (const config of DASHBOARDS) {
  test.describe(`${config.title} — baseline calculations`, () => {
    // Serial so UPDATE mode can accumulate every scenario before writing the file.
    test.describe.configure({ mode: 'serial' });

    const existing = readBaseline(config.key);
    /** @type {Record<string, unknown>} */
    const collected = {};

    test('baseline file exists', () => {
      test.skip(UPDATE, 'regenerating baselines');
      expect(
        existing,
        `Missing ${baselinePath(config.key)} — run: npm run test:case-studies:update`
      ).not.toBeNull();
    });

    for (const [name, inputs] of Object.entries(config.scenarios)) {
      test(`scenario: ${name}`, async ({ page }) => {
        const actual = await runScenario(page, config, inputs);

        if (UPDATE) {
          collected[name] = { inputs, outputs: actual };
          return;
        }

        const expected = existing && existing.scenarios && existing.scenarios[name];
        expect(
          expected,
          `No baseline for scenario "${name}" — run: npm run test:case-studies:update`
        ).toBeTruthy();

        expect(actual.scalars).toEqual(expected.outputs.scalars);
        expect(actual.tables).toEqual(expected.outputs.tables);
      });
    }

    test.afterAll(() => {
      if (!UPDATE) return;
      writeBaseline(config.key, {
        dashboard: config.key,
        title: config.title,
        note: 'Generated by tests/case_studies/case-studies.calc.spec.js. Do not hand-edit; regenerate with npm run test:case-studies:update.',
        scenarios: collected,
      });
    });
  });
}
